<?php
include_once("../db_config.php");
include('relation_class.php');
//$staffid='C003';
//$coursecode='BICCIC601';
//$section_id=1;
$details=$_GET['value'];
$details=explode(",",$details);
	$midsem_name=$details[1];
	$section_id=$details[2];
	$coursecode=$details[3];
	$staffid=$details[0];
	$sno=0;
	//$a='0000-00-00 00:00:00';
$relation_obj1 = new relation_class();
$students=$relation_obj1-> listofstudents_staff($staffid,$section_id,$coursecode);
$marks=$relation_obj1-> getmidsem_marks($staffid,$section_id,$coursecode);
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>
SASTRA University - SRC
</title>
</head>
<body>
<?php
// Require the class
require_once('pdf/HTML_ToPDF.php');

// Full path to the file to be converted
$htmlFile = ('write.html');
// The default domain for images that use a relative path
// (you'll need to change the paths in the test.html page 
// to an image on your server)
$defaultDomain = 'www.rustyparts.com';
// Full path to the PDF we are creating
$pdfFile = ('timecard.pdf');
// Remove old one, just to make sure we are making it afresh
@unlink($pdfFile);

// Instnatiate the class with our variables
$pdf =& new HTML_ToPDF($htmlFile, $defaultDomain, $pdfFile);
// Set headers/footers
$pdf->setHeader('color', 'blue');
$pdf->setFooter('left', 'Generated by HTML_ToPDF');
$pdf->setFooter('right', '$D');
$result = $pdf->convert();

// Check if the result was an error
if (is_a($result, 'HTML_ToPDFException')) {
    die($result->getMessage());
}
else {
    echo "PDF file created successfully: $result";
    echo '<br />Click <a href="' . basename($result) . '">here</a> to view the PDF file.';
}
?>
<table border = 1 cellspacing=0 cellpadding=0 align="center" id="mytable">
<tr>
<th>Sno</th>
<th>Regno</th>
<th>Name</th>
<th><center>Mid-I</center></ br>
	<center>50 | 20</center>
</th>
<th><center>Mid-II</center></ br>
	<center>50 | 20</center>
</th>
<th><center>Mid-III</center></ br>
	<center>50 | 20</center>
</th>
<th><center>Internals</center></th>
<th><center>Total</center></th>
</tr>
<?php
while($row2=mysql_fetch_array($students) and $row3=mysql_fetch_array($marks))
{ 
	$sno++;
	
?>
<tr>
<td><?php echo $sno; ?></td>
<td><?php echo $row2[1]; ?></td>
<td><?php echo ucwords($row2[0]); ?></td>
<td align="center">
	<?php  
    if($row3[0]=='121')
				{ 
				echo "<span>A</span>"; 
				}
				else { echo ($row3[0]*(10/4)); }?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php if($row3[0]=='121')
				{ 
				echo "<span>A</span>"; 
				}
				else { echo $row3[0]; }?>
</td>
<td align="center">
<?php  
    if($row3[1]=='121')
				{ 
				echo "<span>A</span>"; 
				}
				else { echo ($row3[1]*(10/4)); }?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php if($row3[1]=='121')
				{ 
				echo "<span>A</span>"; 
				}
				else { echo $row3[1]; }?>
</td>
<td align="center">
<?php  
    if($row3[2]=='121')
				{ 
				echo "<span>A</span>"; 
				}
				else { echo ($row3[2]*(10/4)); }?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php if($row3[2]=='121')
				{ 
				echo "<span>A</span>"; 
				}
				else { echo $row3[2]; }?>
</td>

<td><?php echo $row3[3]; ?></td>
<?php 
$marks_sort=array();
$marks_sort[0]=$row3[0];
$marks_sort[1]=$row3[1];
$marks_sort[2]=$row3[2];
$i=0; 
while($i<=2)
{
if($marks_sort[$i]==121)
{
$marks_sort[$i]=0;
}
$i++;
}
sort($marks_sort);
?>
<td><?php
$p= $marks_sort[1] + $marks_sort[2] + $row3[3];
echo $p;
?>
</td>
</tr>
<?php
 }
 ?>
</table>

</div>
</body>
</html>

